# Generated by Django 4.0.3 on 2022-04-24 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basketball_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_number', models.IntegerField()),
                ('player_position', models.CharField(choices=[('Forward', 'Forward'), ('Center', 'Center'), ('Guard', 'Guard')], max_length=100)),
                ('player_nationality', models.CharField(max_length=100)),
                ('player_image', models.ImageField(upload_to='static/scms_app/images')),
            ],
            options={
                'verbose_name': 'Basketball_Player',
                'verbose_name_plural': 'Basketball_Players',
            },
        ),
        migrations.CreateModel(
            name='Basketball_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basketball_ticket_opponent', models.CharField(max_length=100)),
                ('basketball_ticket_location', models.CharField(max_length=100)),
                ('basketball_ticket_date', models.DateTimeField()),
                ('basketball_ticket_price', models.IntegerField()),
                ('basketball_ticket_count', models.IntegerField()),
                ('basketball_ticket_image', models.ImageField(upload_to='static/scms_app/images')),
            ],
            options={
                'verbose_name': 'Basketball_Ticket',
                'verbose_name_plural': 'Basketball_Tickets',
            },
        ),
        migrations.CreateModel(
            name='Football_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_number', models.IntegerField()),
                ('player_position', models.CharField(choices=[('Forward', 'Forward'), ('Midfielder', 'Midfielder'), ('Defender', 'Defender'), ('Goalkeeper', 'Goalkeeper')], max_length=100)),
                ('player_nationality', models.CharField(max_length=100)),
                ('player_image', models.ImageField(upload_to='static/scms_app/images')),
            ],
            options={
                'verbose_name': 'Football_Player',
                'verbose_name_plural': 'Football_Players',
            },
        ),
        migrations.CreateModel(
            name='Football_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('football_ticket_opponent', models.CharField(max_length=100)),
                ('football_ticket_homeaway', models.CharField(choices=[('H', 'Home'), ('A', 'Away')], max_length=100)),
                ('football_ticket_location', models.CharField(max_length=100)),
                ('football_ticket_date', models.DateTimeField()),
                ('football_ticket_price', models.IntegerField()),
                ('football_ticket_count', models.IntegerField()),
                ('football_ticket_image', models.ImageField(upload_to='static/scms_app/images')),
            ],
            options={
                'verbose_name': 'Football_Ticket',
                'verbose_name_plural': 'Football_Tickets',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('userimage', models.ImageField(default='', upload_to='static/scms_app/images')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Football_Bought_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('football_bought_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scms_app.football_ticket')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Football_Bought_Ticket',
                'verbose_name_plural': 'Football_Bought_Tickets',
            },
        ),
        migrations.CreateModel(
            name='Basketball_Bought_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basketball_bought_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scms_app.basketball_ticket')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Basketball_Bought_Ticket',
                'verbose_name_plural': 'Basketball_Bought_Tickets',
            },
        ),
    ]
