# Generated by Django 4.0.3 on 2022-04-18 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_opponent', models.CharField(max_length=100)),
                ('ticket_homeaway', models.CharField(choices=[('H', 'Home'), ('A', 'Away')], max_length=100)),
                ('ticket_location', models.CharField(max_length=100)),
                ('ticket_date', models.DateTimeField()),
                ('ticket_price', models.IntegerField()),
                ('ticket_count', models.IntegerField()),
                ('ticket_image', models.ImageField(upload_to='static/scms_app/images')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
