# Generated by Django 4.0.3 on 2022-04-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userimage',
            field=models.ImageField(default='media/default-user.jpg', upload_to='static/scms_app/images'),
        ),
    ]
