# Generated by Django 4.0.3 on 2022-04-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms_app', '0002_ticket_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basketball_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basketball_ticket_opponent', models.CharField(max_length=100)),
                ('basketball_ticket_location', models.CharField(max_length=100)),
                ('basketball_ticket_date', models.DateTimeField()),
                ('basketball_ticket_price', models.IntegerField()),
                ('basketball_ticket_count', models.IntegerField()),
                ('basketball_ticket_image', models.ImageField(upload_to='static/scms_app/images')),
            ],
            options={
                'verbose_name': 'Basketball_Ticket',
                'verbose_name_plural': 'Basketball_Tickets',
            },
        ),
        migrations.CreateModel(
            name='Football_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('football_ticket_opponent', models.CharField(max_length=100)),
                ('football_ticket_homeaway', models.CharField(choices=[('H', 'Home'), ('A', 'Away')], max_length=100)),
                ('football_ticket_location', models.CharField(max_length=100)),
                ('football_ticket_date', models.DateTimeField()),
                ('football_ticket_price', models.IntegerField()),
                ('football_ticket_count', models.IntegerField()),
                ('football_ticket_image', models.ImageField(upload_to='static/scms_app/images')),
            ],
            options={
                'verbose_name': 'Football_Ticket',
                'verbose_name_plural': 'Football_Tickets',
            },
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
