# Generated by Django 4.0.3 on 2022-04-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms_app', '0003_alter_profile_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userimage',
            field=models.ImageField(default='scms_app/media/default-user.jpg', upload_to=''),
        ),
    ]
