# Generated by Django 4.0.3 on 2022-04-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms_app', '0004_alter_profile_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userbackimage',
            field=models.ImageField(default='scms_app/media/default-back-user.jpg', upload_to=''),
        ),
    ]
