# Generated by Django 4.0.3 on 2022-04-19 13:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scms_app', '0004_football_bought_tickets_basketball_bought_tickets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basketball_Bought_Tickets',
            new_name='Basketball_Bought_Ticket',
        ),
        migrations.RenameModel(
            old_name='Football_Bought_Tickets',
            new_name='Football_Bought_Ticket',
        ),
    ]
