# Generated by Django 4.0.3 on 2022-04-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms_app', '0005_profile_userbackimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
