# Generated by Django 4.0.3 on 2022-04-24 20:11

from django.db import migrations, models
import scms_app.storage


class Migration(migrations.Migration):

    dependencies = [
        ('scms_app', '0006_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userbackimage',
            field=models.ImageField(default='scms_app/media/default-back-user.jpg', storage=scms_app.storage.OverwriteStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userimage',
            field=models.ImageField(default='scms_app/media/default-user.jpg', storage=scms_app.storage.OverwriteStorage(), upload_to=''),
        ),
    ]
