# Generated by Django 4.0.3 on 2022-04-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scms_app', '0007_alter_profile_userbackimage_alter_profile_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketball_bought_ticket',
            name='basketball_bought_ticket',
        ),
    ]
