# Generated by Django 4.0.3 on 2022-04-24 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scms_app', '0009_basketball_bought_ticket_basketball_bought_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketball_bought_ticket',
            name='basketball_bought_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scms_app.basketball_ticket'),
        ),
        migrations.AlterField(
            model_name='basketball_bought_ticket',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='football_bought_ticket',
            name='football_bought_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scms_app.football_ticket'),
        ),
        migrations.AlterField(
            model_name='football_bought_ticket',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
