# Generated by Django 4.0.3 on 2022-04-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms_app', '0010_alter_basketball_bought_ticket_basketball_bought_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='football_bought_ticket',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
