# Generated by Django 4.0.3 on 2022-04-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms_app', '0012_alter_football_bought_ticket_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketball_bought_ticket',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
