# Generated by Django 4.0.3 on 2022-04-26 11:41

from django.db import migrations, models
import scms_app.storage


class Migration(migrations.Migration):

    dependencies = [
        ('scms_app', '0017_remove_basketball_bought_ticket_count_tickets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merch_name', models.CharField(max_length=100)),
                ('merch_quantity', models.IntegerField()),
                ('merch_price', models.IntegerField()),
                ('merch_type', models.CharField(choices=[('Full-Kits', 'Full-Kits'), ('Accessories', 'Accessories'), ('Shoes', 'Shoes'), ('Balls', 'Balls'), ('Flags', 'Flags')], max_length=100)),
                ('merch_image', models.ImageField(storage=scms_app.storage.OverwriteStorage(), upload_to='')),
            ],
            options={
                'verbose_name': 'Merchandise',
                'verbose_name_plural': 'AllMerchandise',
            },
        ),
    ]
