# Generated by Django 4.0.3 on 2022-04-26 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scms_app', '0018_merchandise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise_Bought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('merch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scms_app.merchandise')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MerchandiseBought',
                'verbose_name_plural': 'AllMerchandiseBought',
            },
        ),
    ]
