# Generated by Django 4.0.3 on 2022-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms_app', '0019_merchandise_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise_bought',
            name='product_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
