# Generated by Django 4.0.3 on 2022-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms_app', '0020_merchandise_bought_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise_bought',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
