# Generated by Django 4.0.3 on 2022-04-27 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scms_app', '0022_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='SportsNews',
        ),
        migrations.RenameField(
            model_name='sportsnews',
            old_name='news_header',
            new_name='newsHeader',
        ),
        migrations.RenameField(
            model_name='sportsnews',
            old_name='news_image',
            new_name='newsImage',
        ),
        migrations.RenameField(
            model_name='sportsnews',
            old_name='news_text',
            new_name='newsText',
        ),
    ]
