# Generated by Django 4.0.3 on 2022-04-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms_app', '0023_rename_news_sportsnews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsnews',
            name='newsText',
            field=models.CharField(max_length=1000),
        ),
    ]
